# Numpy zero to hero series

In [1]:
# importing library
import numpy as np

In [2]:
#generating array upto any sequence from zero (consecutive number)
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
#generating array in any range(consecutive number)
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
# generating nu,ber with gap of 4
np.arange(10,20,4)

array([10, 14, 18])

In [5]:
# genarating random array data 
data = np.random.rand(4,5)
data

array([[ 0.20351152,  0.04068008,  0.43329307,  0.05026897,  0.3962553 ],
       [ 0.30673963,  0.81020668,  0.05480509,  0.47136827,  0.22139388],
       [ 0.66085778,  0.39912077,  0.59434802,  0.43416814,  0.60174287],
       [ 0.86165148,  0.55803608,  0.68271046,  0.79763289,  0.70084973]])

In [6]:
data*1000

array([[ 203.51152462,   40.68007528,  433.29307171,   50.26896511,
         396.25530018],
       [ 306.73963449,  810.20668233,   54.80508893,  471.36827481,
         221.39387644],
       [ 660.85778234,  399.12076749,  594.3480224 ,  434.16814129,
         601.74287254],
       [ 861.65148138,  558.03608016,  682.71045994,  797.63289023,
         700.84972702]])

In [7]:
data+100

array([[ 100.20351152,  100.04068008,  100.43329307,  100.05026897,
         100.3962553 ],
       [ 100.30673963,  100.81020668,  100.05480509,  100.47136827,
         100.22139388],
       [ 100.66085778,  100.39912077,  100.59434802,  100.43416814,
         100.60174287],
       [ 100.86165148,  100.55803608,  100.68271046,  100.79763289,
         100.70084973]])

In [8]:
print('Shape::',data.shape)
print('Dtype::',data.dtype)

Shape:: (4, 5)
Dtype:: float64


In [9]:
# creating array from a list 
a = [46, 7, 8, 9]
b = [[4, 5, 6], [8, 93, 4]]
c = [[8, 9, 10, 22], [9, 10, 98, 67], [83, 38, 32, 43]]
arr1 = np.array(a)
arr2 = np.array(b)
arr3 = np.array(c)

In [10]:
#checking dime%nson of array
print('Array1 Dimension {} Shape {}'.format(arr1.ndim, arr1.shape))
print('Array2 Dimesnion {} Shape {}'.format(arr2.ndim, arr2.shape))
print('Array3 Dimension {} Shape {}'.format(arr3.ndim, arr3.shape))

Array1 Dimension 1 Shape (4,)
Array2 Dimesnion 2 Shape (2, 3)
Array3 Dimension 2 Shape (3, 4)


In [11]:
# Creating 1D zeros array
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [12]:
# Creating 2D zeros array
np.zeros((5, 5 ))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print('Array1::', arr1)
print('Array2::', arr2)

Array1:: [ 1.  2.  3.]
Array2:: [1 2 3]


In [14]:
# Converting dtypw
float_arr = arr2.astype(np.float64)
print(float_arr)

[ 1.  2.  3.]


In [15]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

In [16]:
print('Addition::\n', arr1 + arr1)
print('Subtraction::\n', arr1 - arr1)
print('Multiplication::\n', arr1 * arr1)
print('Array Exponent::\n', arr1 ** 0.5)

Addition::
 [[  2.   4.   6.]
 [  8.  10.  12.]]
Subtraction::
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]
Multiplication::
 [[  1.   4.   9.]
 [ 16.  25.  36.]]
Array Exponent::
 [[ 1.          1.41421356  1.73205081]
 [ 2.          2.23606798  2.44948974]]


In [17]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [18]:
arr2>arr1

array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

In [19]:
# Slicing in Array 
arr = np.arange(10)
arr[5]

5

In [20]:
arr[5:8]

array([5, 6, 7])

In [21]:
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [22]:
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


In [23]:
arr_slice[1] = 12345
print(arr_slice)

[   12 12345    12]


In [24]:
# broad casting
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [25]:
# 2D array 
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [26]:
print('Array::\n', arr2d)
print('\n3rd Row::', arr2d[2])
print('\n3rd element of 1st row::', arr2d[0,2])

Array::
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3rd Row:: [7 8 9]

3rd element of 1st row:: 3


In [27]:
# 3D Array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
# generating copies
old_values = arr3d[0].copy()

# broadcasting value
arr3d[0] = 42

print("Broadcasted Array", )
print(arr3d[0, 0])

Broadcasted Array
[42 42 42]


In [33]:
# slicing a 1D array  
arr = np.array([4, 5, 6, 9, 8, 6, 3, 1, 10])
print('Sliced array::', arr[:5])

Sliced array:: [4 5 6 9 8]


In [43]:
# slicing  in 2D array 
print("Array::\n", arr2d)
print('Array slicing\n', arr2d[:2])
print('Array by using Multiple slicing::\n',arr2d[:2, 1:])
print('Array by using Multiple slicing::\n',arr2d[1, 1:3])

Array::
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array slicing
 [[1 2 3]
 [4 5 6]]
Array by using Multiple slicing::
 [[2 3]
 [5 6]]
Array by using Multiple slicing::
 [5 6]


In [64]:
# Boolean Indexing
names = np.array(['python', 'ss', 'technology', 'ml', 'ai', 'ds', 'ab'])
data = np.random.randn(7, 4)
data

array([[ 0.6406348 , -1.50691453,  0.89314458,  1.08691385],
       [-0.18260442, -1.52839581,  0.43515829, -1.9343553 ],
       [ 0.39044951,  1.34674993, -1.49286407,  0.21840634],
       [-1.36249543, -0.14067545, -0.5257946 ,  0.7751083 ],
       [-1.14509194, -0.28906319, -0.17024302,  0.68863477],
       [-1.00399217, -1.18205525,  0.63968252, -0.38335027],
       [ 0.12456124, -0.57767043,  2.28069381,  3.12354446]])

In [52]:
print("Boolean response::\n", names == 'python')
print("Boolean values applying to data::\n", data[names == 'python'])

Boolean response::
 [ True False False False False False False]
Boolean values applying to data::
 [[-0.93358418  0.0823013  -1.8758688   0.37487863]]


In [54]:
data[names == 'python']

array([[-0.93358418,  0.0823013 , -1.8758688 ,  0.37487863]])

In [56]:
data[names == 'python', 2:]

array([[-1.8758688 ,  0.37487863]])

In [60]:
data[~(names != 'python')]

array([[-0.93358418,  0.0823013 , -1.8758688 ,  0.37487863]])

In [66]:
mask = (names == 'python') | (names == 'ss')
data[mask]

array([[ 0.6406348 , -1.50691453,  0.89314458,  1.08691385],
       [-0.18260442, -1.52839581,  0.43515829, -1.9343553 ]])

In [67]:
data[data < 0] = 0
print("Data::", data)

Data:: [[ 0.6406348   0.          0.89314458  1.08691385]
 [ 0.          0.          0.43515829  0.        ]
 [ 0.39044951  1.34674993  0.          0.21840634]
 [ 0.          0.          0.          0.7751083 ]
 [ 0.          0.          0.          0.68863477]
 [ 0.          0.          0.63968252  0.        ]
 [ 0.12456124  0.          2.28069381  3.12354446]]


In [69]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]


In [70]:
arr = np.arange(32).reshape((8, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [71]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])